[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x7bf86f850eae010ebcf5560b0a5196ed0e720409dda0152cac0622ef1d23dff6'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]